name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${ secrets.POSTMAN_API_KEY }
      - name: Run API tests
        run: |
          postman collection run "46101819-77e1f24d-7e33-427c-909b-6d4e1f05dd8d"